name: 'Auto Assign Issue'

on:
  issues:
    types:
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: peter-evans/assign-issue@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "amsmith41"
